### ISSUE TITLE
User can't see detections for Tag they own

### ISSUE THREAD

**Issue by dnahodil** [aodn/aatams#145]
Via the helpdesk. Reported by [Paul Butcher](https://aatams.emii.org.au/aatams/person/show/30369904)

> I am currently downloading detections from the IMOS database and I came across a problem. One of my tags  states there were 17 detections but database doesn’t show what these are on the CSV file or the main page. However, they do pop up on the KMZ tag tracks and bubble plot.
>
> The tag in question is A69-9001-27680

Was the user logged in at the time?
> Yes I was logged in and even logged out several times to see if this was the problem.

**Comment by jonescc** [comment]
Unable to reproduce this on a copy of the production database, using what I think is the current production software logged in as Paul Butcher.  I'm able to see all 17 detections in the csv file and through the user interface.

The detections were uploaded in September and the problem reported on the 20th November so its unlikely an issue with the materialised view not having been refreshed at the time.

Looks like there was a release of aatams just after this problem was reported, so there may have been fixes in that release that resolved this issue.

@kereid, can we find out if this problem is still occurring for Paul and if so find out exactly what steps he is taking to get this to happen.

**Comment by kereid** [comment]
Ok I will email him to find out :-)

**Comment by kereid** [comment]
Still waiting for him to respond

**Comment by xhoenner** [comment]
> Unable to reproduce this on a copy of the production database, using what I think is the current production software logged in as Paul Butcher. I'm able to see all 17 detections in the csv file and through the user interface.

@kereid: :+1:, tried the exact same thing and could retrieve all 17 detections, should we close that bug as Paul still hasn't responded to your email?

**Comment by ktattersall** [comment]
@kereid @xhoenner I think we can close this if we haven't heard back from Paul, and if we can't reproduce the bug.

**Comment by kereid** [comment]
Sorry I had that on my list from @xhoenner 's requests last Thursday, yep will close if was still broken I believe he would have followed up again.
