### ISSUE TITLE
Tag ID's not showing up in DB

### ISSUE THREAD

**Issue by kereid** [aodn/aatams#193]
Reported by Andre on behalf of Jayson Semmens:

During the latest downloads of the Maria Island and Cape Barren arrays, the attached tag IDs were detected by receivers and do show up in the corresponding downloaded vrl files. However, after uploading them, Jayson didn’t get any confirmation.

Wasn’t that an issue with other people and related data not long ago? Would you mind looking into this, pls? Thanks!

Reply:

are you able to let us know which upload you are talking about (i.e. which one from https://aatams.emii.org.au/aatams/receiverDownloadFile/list?sort=importDate&order=desc

Reply:

I think this is a download, for example, that he was talking about:

31/01/2013 09:42:46	Maria Island Jan 2013 detections.csv

**Comment by jkburges** [comment]
Ref: https://aatams.emii.org.au/aatams/receiverDownloadFile/show/43698926

**Comment by jkburges** [comment]
"... after uploading them, Jayson didn’t get any confirmation" - I'm not quite sure exactly what this means - does it mean that he didn't get emails about new detections for his tags?  Was the tag metadata in the DB at the time the receiver data was uploaded (31/01/2013, by Andre) - this is required so that the system knows who to notify.

@kereid can we please follow up on this, it's not clear to me what the problem is.

**Comment by xhoenner** [comment]
I downloaded that detection file, which is made of 65 detections from 4 distinct transmitters.
I then had a look in the web app and could find all these detections when looking for those transmitters in the Tag Detection page.

As @jkburges not sure what the issue is, is it that Jayson didn't get a confirmation after having uploaded his file? @kereid would you mind sending Andre an email asking him to (1) watch the AATAMS repo so that we can reference him, and (2) be more specific on that particular issue.

**Comment by kereid** [comment]
@xhoenner I'll email him now and see if he can provide more info.

**Comment by xhoenner** [comment]
@jkburges seems to me that this issue can be closed too.
