### ISSUE TITLE
Data licence and use limitations, data citation

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#292]
Currently there's no pop-up window on the AATAMS web app when people download detections through the [Tag Detections page](https://aatams.emii.org.au/aatams/detection/list). The data committee would like a similar pop-up as the one on Step 3 of the portal
![screen shot 2016-03-16 at 11 40 39 am](https://cloud.githubusercontent.com/assets/3443821/13798655/b8ab38b0-eb6c-11e5-9f48-1047939563cc.jpg)

Furthermore, since IMOS only funds some receivers and no tag, additional fields are needed in the CSVs that people download, namely for each detection we need the email address of (1) the person owning the receiver, and (2) the person owning the tag.

That's all I can think of, any suggestion @smancini, @atkinsn, @jachope?

**Comment by atkinsn** [comment]
I have looked back through my notes - and had a meeting with @jachope and Marian on 7th of May last year. We discussed the need to have a specific AATAMS data acknowledgement page, with a division of whether it was IMOS data or "other". We needed to provide guidance on how to determine the citable party - wasn't clear from current set-up. And therefore do we need to make it clear? So then Jac and I, had a meeting with @xhoenner . We spoke about marking the IMOS data as "IMOS", add a column? identify by project? All others are therefore "non-IMOS". 
So I am thinking that something would of been generated by Jac at the time to go on backlog??

**Comment by jachope** [comment]
Thought I commented on this last Wed, but must have not pressed the right buttons - I was in a rush!

Nat's recollection is correct in that we were looking at ways that we could advise users to identify the owners of the AATAMS collections and therefore cite and acknowledge data use correctly.  We knew this was going to become increasingly important with other (non-IMOS) data providers.  We were discussing the ability to identify a project (see email to Jon & Kate posted below).  We were going to load details into the User Guide as for the FY15/16 we had insufficient resources to complete any new feature implementation in the app, the focus would be on bug correction.

At the time Nat suggested that metadata wouldn't be the answer as there is not a metadata record for every collection scenario i.e. ownership and citation requirements.  Without the required metadata how would we achieve what Xav is suggesting in the CSV?


_____
Hi Jac,

The answer is... it depends.

It is not straight forward since the detection data is a combination of both tag data and receiver data, each of which is often owned by different organisations.
Aside from that, most things in the DB are associated with a project, as you note.  Each project is associated with one or more organisations - so you can derive ownership based on that.

But it depends on how you classify data which is "owned" or comes from a combination of sources.

Let me know if you have more questions about this.

Jon

________________________________________
From: Jacqui Hope
Sent: Friday, 8 May 2015 3:11 PM
To: Kate Reid; Jon Burgess
Subject: AATAMS - App/database 
 
Hi Kate & Jon,
 
I am wondering if it is possible to identify either within the database, from reports or within a data download which data is IMOS data or which is not?  If it is possible how is it exposed?  I am assuming that it is possible to tell based on project i.e. if the project name starts with AATAMS then we would know it is IMOS, but I am thinking there must be another (better?) way?
 
Thanks
Jac

**Comment by fjaine** [comment]
Hi there,

I have recently received a few inquiries from community members about the right way to reference IMOS, ATF and data issued from the database in scientific papers. 

It would be good to add a citation template for users to follow on the web app, somewhere on the Homepage or in a new tab in the left menu maybe? 

Something like this (feel free to edit as you see appropriate):

**Please acknowledge the IMOS Animal Tracking Acoustic Database in publications using the below wording:**

_In a manucript:_
“Data was sourced from the Animal Tracking Database (https://animaltracking.aodn.org.au) of the Integrated Marine Observing System (IMOS, www.imos.org.au) - IMOS is a national collaborative research infrastructure supported by the Australian Government. The database is a central acoustic telemetry data repository maintained by the IMOS Animal Tracking Facility (ATF).”
 
_In a list of references:_ 
IMOS [year-of-data-download], Animal Tracking Database, http://animaltracking.aodn.org.au, accessed [date-of-access].

**Comment by atkinsn** [comment]
Hi Fabrice, 

I was going to start by pointing out that we have some of this in a aatams github issue already - but just noticed its this one!

So as you can see above - one of the things we need to achieve in the future is to be able to identify who are the citable parties in relation to data that people download - but I am sure we will get there in the future!

We do currently provide a suggestion citation at the following place (which you have probably seen):

- All animal tracking metadata records associated with the Portal:
The citation in a list of references is: "IMOS [year-of-data-download], [Title], [data-access-URL], accessed [date-of-access]." 
Any users of IMOS data are required to clearly acknowledge the source of the material derived from IMOS in the format: "Data was sourced from the Integrated Marine Observing System (IMOS) - IMOS is a national collaborative research infrastructure, supported by the Australian Government." If relevant, also credit other organisations involved in collection of this particular datastream (as listed in 'credit' in the metadata record). 

Based on previous meetings we have a the link to the Acknowledgement page added (at the bottom of the homepage) - https://help.aodn.org.au/user-guide-introduction/aodn-portal/data-use-acknowledgement/, which I helped write, but there isn't a suggested citation there either (you have to follow the link to the IMOS data policy). So I will work with Kate - @kereid  to provide a clearer path from this page to both the suggested acknowledgement and citation from this page.

Your suggested "data was sourced...: statement and reference citation may be able to be put onto the homepage and I think the most appropriate place - and good as it also jumps out at you - is the the Acknowledgement box on the home page - above the CAAB reference. BUT before we do this, we need to run this past the IMOS Office and some people here (some of whom are on leave), both for its placement on the homepage (as @jachope and @kereid have worked hard to simplify the process around future edits of this information), and for making it Animal Tracking specific.

So happy to pop along and chat whilst you are still in town, but otherwise, will get back to on the suggested points above.

**Comment by xhoenner** [comment]
An update from @fjaine on this issue which supersedes https://github.com/aodn/aatams/issues/292#issuecomment-270294118.
* change the descriptive text about the database on the homepage as it's outdated, @fjaine to provide more details.
* the paragraphs below should be added to the web app homepage, into the Acknowledgments box. Note the link to the attached pdf in the last sentence. @fjaine you'll need to modify this pdf so that the name of the database is consistent with the text below, *i.e.* change 'IMOS ATF Acoustic Animal Tracking Database' to 'IMOS Animal Tracking Database' throughout.

### Acknowledging the IMOS Animal Tracking Database:

Any use of the acoustic telemetry data obtained through the [IMOS Animal Tracking Database](https://animaltracking.aodn.org.au) and/or the [AODN online portal](https://portal.aodn.org.au/) requires the following acknowledgement and citation:
 
*In the Acknowledgments:*
“Data was sourced from the Animal Tracking Database (https://animaltracking.aodn.org.au) of the Integrated Marine Observing System (IMOS, www.imos.org.au) - IMOS is a national collaborative research infrastructure, supported by Australian Government. It is operated by a consortium of institutions as an unincorporated joint venture, with the University of Tasmania as Lead Agent. The database is a centralised acoustic telemetry data repository maintained by the IMOS Animal Tracking Facility (IMOS ATF, http://imos.org.au/facilities/animaltracking/) and the Australian Ocean Data Network (AODN, https://portal.aodn.org.au/ ).”
 
*In the Reference List:*
IMOS [year-of-data-download], Animal Tracking Database, http://animaltracking.aodn.org.au, accessed [date-of-access].
 

### Using data from the IMOS Animal Tracking Database:
For use of the contents of the [IMOS Animal Tracking Database](https://animaltracking.aodn.org.au), the [IMOS Animal Tracking Facility (IMOS ATF)](http://imos.org.au/facilities/animaltracking/) recommends adhering to the [*Recommended guidelines for using data sourced from the IMOS Animal Tracking Database*](https://github.com/aodn/aatams/files/1250905/Recommended.guidelines.for.using.data.from.the.IMOS.ATF.Acoustic.Animal.Tracking.Database_July2017.pdf).

**Comment by atkinsn** [comment]
@xhoenner will reinitiate conversation about this amongst the relevant peoples here. Apologies for the radio silence our end.

**Comment by jachope** [comment]
Jac & Seb discussed this a few days ago.
The issue needs to be assigned to Seb and he will add it to the Top of the Backlog so that the App changes can be included into an iteration.

**Comment by xhoenner** [comment]
Closing as addressed by https://github.com/aodn/aatams/pull/409.
