### ISSUE TITLE
Implement constraints on transmitter type based on code map value

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#373]
A lot of tags have been assigned to a wrong type of transmitter (see https://github.com/aodn/aatams/issues/240#issuecomment-251265242) and there's currently no logic in the GUI constraining transmitter type based on a particular code map value. The logic detailed below needs to be implemented when users create a tag or edit an existing one.

@fjaine indicated in https://github.com/aodn/aatams/issues/240#issuecomment-264071906 the type of transmitters for each code space:
  * A69-1601, A69-9001: PINGER or RANGE TEST
  * A69-9002, A69-9004, A69-9006: TEMPERATURE, PRESSURE, or ACCELEROMETER

I don't think A180 tags are being used anymore, are they @fjaine ? @bhasin85 no constraint can be implemented on A69-1105 and A69-1206.

**Comment by fjaine** [comment]
@xhoenner A180 tags are similar tags but transmit at 180 kHz instead 69 kHz (hence A180 instead of A69) - they still are valid tag code spaces/IDs, however much less common in our community as they are generally for different types of applications (i.e. smaller fish, freshwater systems, etc.). 

They are still valid though.
