### ISSUE TITLE
'Custom Validation' ERROR when deploying a receiver

### ISSUE THREAD

**Issue by xhoenner** [aodn/aatams#385]
Migrated from https://github.com/aodn/aatams-content/issues/60, originally reported by @fjaine.

@xhoenner I tried to deploy two receivers as part of the AATAMS Glenelg installation:

Receiver 101686: deployed 4/8/16 at GL 7 Station
Receiver 101679: deployed 4/8/16 at GL 8 Station
There is no deployment time available for these deployments (not recorded on the day) so I left it as 00:00 UTC.

When creating the deployment, the following error appeared. Any idea what's preventing me from deploying these receivers?

![screen shot 2017-02-09 at 2 34 28 am](https://cloud.githubusercontent.com/assets/22288128/22769416/51d9d340-ee80-11e6-86fc-2b3e9ed02b95.png)

**Comment by xhoenner** [comment]
@pblain, @smancini tested on aatams-dev-instance and consistently got the same error as in @fjaine's comment above, no matter which receiver I selected. It seems therefore impossible for users to create a new receiver deployment record, hence this issue should be a VIT.

**Comment by fjaine** [comment]
@xhoenner @smancini @pblain can you please update me on where we are at with this issue - any idea where it arises from and when we should have it resolved? I have received emails from another user reporting the issue and I need to get back to them.

**Comment by julian1** [comment]
If I had to guess, I would suspect, https://github.com/aodn/aatams/commit/e250b9664ffa2ee02a85c8769186d783604b08d0. There is complicated validation between deploymentDateTime and initialisationDateTime.

**Comment by xhoenner** [comment]
@fjaine, waiting to hear from @pblain who's attending the IMOS planning meeting this week. So not sure anyone will look at this issue before next week...

**Comment by fjaine** [comment]
@xhoenner @pblain any update on this? 

We still have users waiting to update their receiver deployment details, and our team has come back from the field with quite a few receiver deployments to enter too.

**Comment by xhoenner** [comment]
One of our developers will look at this issue this week, I know it's a pressing matter for you guys so we'll try to get that fixed ASAP.

**Comment by julian1** [comment]
GL 7
VR2W-101686

**Comment by julian1** [comment]
https://github.com/aodn/aatams/compare/fix_385?expand=1

Validation has been relaxed in the case of a new deployment - where we simply verify that all prior deployments have a recovered status. This prevents the user from being able to create an entry for a new deployment if the receiver was never recovered.

It would be much nicer if these checks were enforceable at the database level rather than in application code. But it's difficult because of the table join, and because the checks involve multiple rows. Perhaps should be using a validation function() and trigger. 

Note, that the error messages with nice human readable text are not being formatting correctly in the resulting error page. I'm treating this as a separate issue/regression.

**Comment by fjaine** [comment]
Great! Thanks @julian1 

Trying to deploy a receiver now to check that it's all good :)

**Comment by fjaine** [comment]
Still getting an error message @julian1 
![database deployment error](https://cloud.githubusercontent.com/assets/22288128/23244059/e706e50a-f9d6-11e6-9e0b-e34930dc9ba7.jpg)

**Comment by julian1** [comment]
Hi @fjaine I've deployed to an internal server for @xhoenner to test. If he says ok, then I'll deploy it to production tomorrow.

**Comment by julian1** [comment]
deployed to https://animaltracking.aodn.org.au/
